Fix COLLATE column_constraint (#77)
Was getting this error for migration files contains COLLATE

```
java.lang.AssertionError: Test failed because the compile output unexpectedly has the errors <[
    1.s line 3:19 - ')', ',', <column constraint real> or '[]' expected, got 'COLLATE'
]>. 
```

Fix is to just import COLLATE.