Bump org.postgresql:postgresql from 42.7.0 to 42.7.1 (#71)
Bumps [org.postgresql:postgresql](https://github.com/pgjdbc/pgjdbc) from
42.7.0 to 42.7.1.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/pgjdbc/pgjdbc/releases">org.postgresql:postgresql's
releases</a>.</em></p>
<blockquote>
<h2>v42.7.1</h2>
<h2>Changes</h2>
<ul>
<li>prepared for release 42.7.1 update changelogs <a
href="https://github.com/davecramer"><code>@​davecramer</code></a> (<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3037">#3037</a>)</li>
<li>fix: avoid timezone conversions when sending LocalDateTime to the
database <a href="https://github.com/vlsi"><code>@​vlsi</code></a> (<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2852">#2852</a>)</li>
<li>Apply connectTimeout before SSLSocket.startHandshake to avoid
infinite wait in case the connection is broken <a
href="https://github.com/davecramer"><code>@​davecramer</code></a> (<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3040">#3040</a>)</li>
<li>fix: support waffle-jna 2.x and 3.x by using reflective approach for
ManagedSecBufferDesc <a
href="https://github.com/chrullrich"><code>@​chrullrich</code></a> (<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2720">#2720</a>)</li>
<li>perf: improve performance of PreparedStatement.setBlob,
BlobInputStream, and BlobOutputStream with dynamic buffer sizing <a
href="https://github.com/vlsi"><code>@​vlsi</code></a> (<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3044">#3044</a>)</li>
<li>chore: use java.release=8 when building pgjdbc from the generated
source distribution <a
href="https://github.com/vlsi"><code>@​vlsi</code></a> (<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3038">#3038</a>)</li>
<li>chore: use Java 17 for building pgjdbc, and use --release 8 to
target Java 8, add tests with Java 21 and 22 <a
href="https://github.com/vlsi"><code>@​vlsi</code></a> (<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3026">#3026</a>)</li>
<li>fedora/rpm: move source build to java-17-openjdk-devel <a
href="https://github.com/praiskup"><code>@​praiskup</code></a> (<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3036">#3036</a>)</li>
<li>Revert &quot;Use canonical DateStyle name (<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2925">#2925</a>)&quot;
<a href="https://github.com/vlsi"><code>@​vlsi</code></a> (<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3035">#3035</a>)</li>
<li>Revert &quot;feat: support SET statements combining with other
queries with semicolon in PreparedStatement&quot; <a
href="https://github.com/vlsi"><code>@​vlsi</code></a> (<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3010">#3010</a>)</li>
<li>Update site 42 7 0 <a
href="https://github.com/davecramer"><code>@​davecramer</code></a> (<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3004">#3004</a>)</li>
</ul>
<h2>🧰 Maintenance</h2>
<ul>
<li>chore: bump Gradle to 8.5 <a
href="https://github.com/vlsi"><code>@​vlsi</code></a> (<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3045">#3045</a>)</li>
</ul>
<h2>⬆️ Dependencies</h2>
<!-- raw HTML omitted -->
<ul>
<li>fix(deps): update dependency
org.checkerframework:org.checkerframework.gradle.plugin to v0.6.36 <a
href="https://github.com/renovate-bot"><code>@​renovate-bot</code></a>
(<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3060">#3060</a>)</li>
<li>chore(deps): update plugin biz.aqute.bnd.builder to v7 <a
href="https://github.com/renovate-bot"><code>@​renovate-bot</code></a>
(<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3034">#3034</a>)</li>
<li>fix(deps): update dependency
com.github.spotbugs:com.github.spotbugs.gradle.plugin to v6 <a
href="https://github.com/renovate-bot"><code>@​renovate-bot</code></a>
(<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3056">#3056</a>)</li>
<li>fix(deps): update dependency
com.github.spotbugs:com.github.spotbugs.gradle.plugin to v5.2.5 <a
href="https://github.com/renovate-bot"><code>@​renovate-bot</code></a>
(<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3032">#3032</a>)</li>
<li>chore(deps): update codecov/codecov-action digest to b0466b4 <a
href="https://github.com/renovate-bot"><code>@​renovate-bot</code></a>
(<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3059">#3059</a>)</li>
<li>fix(deps): update checkerframework to v3.41.0 <a
href="https://github.com/renovate-bot"><code>@​renovate-bot</code></a>
(<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3058">#3058</a>)</li>
<li>fix(deps): update logback to v1.2.13 <a
href="https://github.com/renovate-bot"><code>@​renovate-bot</code></a>
(<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3053">#3053</a>)</li>
<li>chore(deps): update codecov/codecov-action digest to 438fa9e <a
href="https://github.com/renovate-bot"><code>@​renovate-bot</code></a>
(<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3051">#3051</a>)</li>
<li>fix(deps): update dependency spotbugs to v4.8.2 <a
href="https://github.com/renovate-bot"><code>@​renovate-bot</code></a>
(<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3052">#3052</a>)</li>
<li>chore: bump Gradle to 8.5 <a
href="https://github.com/vlsi"><code>@​vlsi</code></a> (<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3045">#3045</a>)</li>
<li>fix(deps): update dependency org.ops4j.pax.url:pax-url-aether to
v2.6.14 <a
href="https://github.com/renovate-bot"><code>@​renovate-bot</code></a>
(<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3030">#3030</a>)</li>
<li>chore(deps): update plugin org.nosphere.gradle.github.actions to
v1.4.0 <a
href="https://github.com/renovate-bot"><code>@​renovate-bot</code></a>
(<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3031">#3031</a>)</li>
<li>chore(deps): update dependency ubuntu to v22 <a
href="https://github.com/renovate-bot"><code>@​renovate-bot</code></a>
(<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3033">#3033</a>)</li>
<li>fix(deps): update checkerframework <a
href="https://github.com/renovate-bot"><code>@​renovate-bot</code></a>
(<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3027">#3027</a>)</li>
<li>fix(deps): update dependency spotbugs to v4.8.1 <a
href="https://github.com/renovate-bot"><code>@​renovate-bot</code></a>
(<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3023">#3023</a>)</li>
<li>fix(deps): update dependency uk.org.webcompere:system-stubs-jupiter
to v2.1.5 <a
href="https://github.com/renovate-bot"><code>@​renovate-bot</code></a>
(<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3024">#3024</a>)</li>
<li>fix(deps): update jmh to v1.37 <a
href="https://github.com/renovate-bot"><code>@​renovate-bot</code></a>
(<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3025">#3025</a>)</li>
<li>fix(deps): update dependency com.google.errorprone:error_prone_core
to v2.23.0 <a
href="https://github.com/renovate-bot"><code>@​renovate-bot</code></a>
(<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3022">#3022</a>)</li>
<li>fix(deps): update junit5 monorepo to v5.10.1 <a
href="https://github.com/renovate-bot"><code>@​renovate-bot</code></a>
(<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3015">#3015</a>)</li>
<li>chore(deps): update plugin com.github.burrunan.s3-build-cache to
v1.7 <a
href="https://github.com/renovate-bot"><code>@​renovate-bot</code></a>
(<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3016">#3016</a>)</li>
<li>chore(deps): update dependency com.typesafe.play:sbt-plugin to
v2.9.0 <a
href="https://github.com/renovate-bot"><code>@​renovate-bot</code></a>
(<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3021">#3021</a>)</li>
<li>fix(deps): update dependency checkstyle to v10.12.5 <a
href="https://github.com/renovate-bot"><code>@​renovate-bot</code></a>
(<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3020">#3020</a>)</li>
<li>chore(deps): update codecov/codecov-action digest to 920a494 <a
href="https://github.com/renovate-bot"><code>@​renovate-bot</code></a>
(<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3019">#3019</a>)</li>
<li>chore(deps): update actions/github-script action to v7 <a
href="https://github.com/renovate-bot"><code>@​renovate-bot</code></a>
(<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3018">#3018</a>)</li>
<li>chore(deps): update actions/checkout action to v4 <a
href="https://github.com/renovate-bot"><code>@​renovate-bot</code></a>
(<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3017">#3017</a>)</li>
<li>chore(deps): update plugin org.jetbrains.kotlin.jvm to v1.9.21 <a
href="https://github.com/renovate-bot"><code>@​renovate-bot</code></a>
(<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2921">#2921</a>)</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/pgjdbc/pgjdbc/blob/master/CHANGELOG.md">org.postgresql:postgresql's
changelog</a>.</em></p>
<blockquote>
<h2>[42.7.1] (2023-12-06 08:34:00 -0500)</h2>
<h3>Changed</h3>
<ul>
<li>perf: improve performance of PreparedStatement.setBlob,
BlobInputStream, and BlobOutputStream with dynamic buffer sizing [PR <a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3044">#3044</a>](<a
href="https://redirect.github.com/pgjdbc/pgjdbc/pull/3044">pgjdbc/pgjdbc#3044</a>)</li>
</ul>
<h3>Fixed</h3>
<ul>
<li>fix: Apply connectTimeout before SSLSocket.startHandshake to avoid
infinite wait in case the connection is broken [PR <a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3040">#3040</a>](<a
href="https://redirect.github.com/pgjdbc/pgjdbc/pull/3040">pgjdbc/pgjdbc#3040</a>)</li>
<li>fix: support waffle-jna 2.x and 3.x by using reflective approach for
ManagedSecBufferDesc [PR <a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2720">#2720</a>](<a
href="https://redirect.github.com/pgjdbc/pgjdbc/pull/2720">pgjdbc/pgjdbc#2720</a>)
Fixes [Issue <a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2690">#2690</a>](<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2720">pgjdbc/pgjdbc#2720</a>).</li>
<li>fix: NoSuchMethodError on ByteBuffer#position When Running on Java 8
when accessing arrays, fixes [Issue <a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3014">#3014</a>](<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3014">pgjdbc/pgjdbc#3014</a>)</li>
<li>Revert &quot;[PR <a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2925">#2925</a>](<a
href="https://redirect.github.com/pgjdbc/pgjdbc/pull/2925">pgjdbc/pgjdbc#2925</a>)
Use canonical DateStyle name&quot; [PR <a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3035">#3035</a>](<a
href="https://redirect.github.com/pgjdbc/pgjdbc/pull/3035">pgjdbc/pgjdbc#3035</a>)
Fixes [Issue <a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3008">#3008</a>](<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3008">pgjdbc/pgjdbc#3008</a>)</li>
<li>Revert &quot;[PR #<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2973">#2973</a>](<a
href="https://redirect.github.com/pgjdbc/pgjdbc/pull/2973">pgjdbc/pgjdbc#2973</a>)
feat: support SET statements combining with other queries with semicolon
in PreparedStatement&quot; [PR <a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3010">#3010</a>](<a
href="https://redirect.github.com/pgjdbc/pgjdbc/pull/3010">pgjdbc/pgjdbc#3010</a>)
Fixes [Issue <a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3007">#3007</a>](<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3007">pgjdbc/pgjdbc#3007</a>)</li>
<li>fix: avoid timezone conversions when sending LocalDateTime to the
database <a
href="https://redirect.github.com/pgjdbc/pgjdbc/pull/3010">#2852</a>
Fixes [Issue <a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/1390">#1390</a>](<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/1390">pgjdbc/pgjdbc#1390</a>)
,[Issue <a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2850">#2850</a>](<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/2850">pgjdbc/pgjdbc#2850</a>)
Closes [Issue <a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/1391">#1391</a>(https://redirect.github.com/pgjdbc/pgjdbc/issues/1391)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/pgjdbc/pgjdbc/commit/27bbccfeb73eec105057e53ae6068faf0e6f40b2"><code>27bbccf</code></a>
fix attribution</li>
<li><a
href="https://github.com/pgjdbc/pgjdbc/commit/bb577e0a7afb0df74a9a00d43896ada2c1dd0dfc"><code>bb577e0</code></a>
prepared for release 42.7.1 update changelogs (<a
href="https://redirect.github.com/pgjdbc/pgjdbc/issues/3037">#3037</a>)</li>
<li><a
href="https://github.com/pgjdbc/pgjdbc/commit/c1a851c02b8690cda8e7b11a594f73ed27aa3189"><code>c1a851c</code></a>
fix: avoid timezone conversions when sending LocalDateTime to the
database</li>
<li><a
href="https://github.com/pgjdbc/pgjdbc/commit/25fdfc33162901143c6c32cbcb332e424da42315"><code>25fdfc3</code></a>
fix(deps): update dependency
org.checkerframework:org.checkerframework.gradle...</li>
<li><a
href="https://github.com/pgjdbc/pgjdbc/commit/244f4c049fadea87ae3875dafbb1d15beb6145c2"><code>244f4c0</code></a>
test: use a fixed 1.0.0-dev-master-SNAPSHOT driver version when testing
with ...</li>
<li><a
href="https://github.com/pgjdbc/pgjdbc/commit/1492c981ad42f8267e68ede7ded90a8d85c657c4"><code>1492c98</code></a>
chore: exclude postgresql 1.0.0-dev-master-SNAPSHOT from Renovate as we
use t...</li>
<li><a
href="https://github.com/pgjdbc/pgjdbc/commit/8cfd00c838f3b0e248345a6cce8d8b9d288d61f9"><code>8cfd00c</code></a>
chore: use allowedVersions to limit Renovate updates</li>
<li><a
href="https://github.com/pgjdbc/pgjdbc/commit/9e22ac005cde507a74404e5d4453eee6c92a859e"><code>9e22ac0</code></a>
chore(deps): update plugin biz.aqute.bnd.builder to v7</li>
<li><a
href="https://github.com/pgjdbc/pgjdbc/commit/9244c0d7bda970008298c6596472bfbdcb31f8d0"><code>9244c0d</code></a>
fix(deps): update dependency
com.github.spotbugs:com.github.spotbugs.gradle.p...</li>
<li><a
href="https://github.com/pgjdbc/pgjdbc/commit/5f48b07a3d02b04f45399651b7f8d333b3963d3e"><code>5f48b07</code></a>
chore: try using different syntax for Renovate from upgrading
system-stubs 1....</li>
<li>Additional commits viewable in <a
href="https://github.com/pgjdbc/pgjdbc/compare/REL42.7.0...REL42.7.1">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=org.postgresql:postgresql&package-manager=gradle&previous-version=42.7.0&new-version=42.7.1)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>